default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: "sqlite3"

test:
  <<: *default
  url: "postgresql://postgres:postgres@localhost:5432/test_database_name"

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
